In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# We read the data first

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df

                    name  kills        date
0                jgwen19     70  2025-02-09
1                Dawnftb     34  2025-02-09
2             Hparso1524     36  2025-02-09
3       MarionnJames2307     61  2025-02-09
4         chickenkampong     47  2025-02-09
5             spikey_001     51  2025-02-09
6          kurtdylan1111     15  2025-02-09
7    nickthegodrider1289     37  2025-02-09
8          jamesplayztv1     50  2025-02-09
9            FrailBailen     25  2025-02-09
10            pancake_w1     32  2025-02-09
11             DcypL_Sky     81  2025-02-09
12         burnfield1k22     53  2025-02-09
13            GGXDArusha     39  2025-02-09
14          jellyy112345     49  2025-02-09
15            buddyboil1     63  2025-02-09
16             tsogoo125     66  2025-02-09
17          SeaV1per1224     58  2025-02-09
18          anathaliakdc     42  2025-02-09
19               pensmen     49  2025-02-09
20              gyftfdko     53  2025-02-09
21  Indonesia_ofMalaysia     47  2025-02-09
22             chanmeme1     51  2025-02-09
23              cn191981     47  2025-02-09
24         Oscarchoyzy24     83  2025-02-09
25           Luqman_indo      7  2025-02-09
26          Liklyboos221     31  2025-02-09
27   midnight_karsonwolf      5  2025-02-09
28            ideacentre     38  2025-02-09